apiVersion: v1
kind: Service
metadata:
  namespace: catalog
  labels:
    app: simple-shop
    component: catalog
  name: catalog
spec:
  ports:
  - port: 7002
  selector:
    app: simple-shop
    component: catalog