apiVersion: v1
kind: ConfigMap
metadata:
  namespace: catalog
  name: serviceconfig
  labels:
    app: simple-shop
    team: beta
data:
  svcconfig: |-
    {
      "logging": {
        "logLevel": {
          "default": "Information"
        },
        "logger": "fluentd"
      },
      
      "bus": {
        "receiveEndpoint": "catalog",
        "host": "queue.data",
        "username": "guest",
        "password": "guest"
      },
      
      "application": {
        "portNumber": 7002
      },
      
      "database": {
        "connectionString": "host=localhost;database=Catalog;password=ABC123!!;username=application"
      }
    }

