apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: catalog
  name: catalog
spec:
  template:
    metadata:
      labels:
        app: simple-shop
        component: catalog
        team: beta
    spec:
      containers:
        - name: catalog
          image: dbonessimplestore/catalog:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /hc
              port: 7001
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /hc
              port: 7002
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 2
            timeoutSeconds: 2
          # resources:
          #   limits:
          #     memory: 512Mi
          #   requests:
          #     memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: serviceconfig
            items:
              - key: svcconfig
                path: stagesettings.json